# -*- coding: utf-8 -*-
"""GSR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eebNiXcIUXr-3RlRfsWFoUs_OGnACjU_
"""

# ═══════════════════════ CELL 1: SETUP ═══════════════════════
print("🚀 Setting up environment...\n")
!pip install openpyxl -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score,
                             accuracy_score, precision_recall_fscore_support,
                             confusion_matrix, classification_report)
from scipy import stats
import joblib
import warnings
warnings.filterwarnings('ignore')

# Visualization settings
sns.set_style("whitegrid")
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (16, 10)
plt.rcParams['font.size'] = 10

print("✅ All packages imported successfully!")
print("✅ Visualization settings configured\n")



import cv2
import pytesseract
import numpy as np
import os
from matplotlib import pyplot as plt

# === CONFIG ===
input_image = "/content/gsr_overall_analysis.png"  # path of your combined graph image
output_folder = "/content/separate_graphs"
os.makedirs(output_folder, exist_ok=True)

# === READ IMAGE ===
img = cv2.imread(input_image)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray, (3,3), 0)
edges = cv2.Canny(blur, 50, 150)

# === FIND CONTOURS ===
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(f"🔍 Found {len(contours)} potential graphs")

# === LOOP THROUGH DETECTED GRAPHS ===
graph_count = 0
for i, cnt in enumerate(contours):
    x, y, w, h = cv2.boundingRect(cnt)

    # Filter out small contours
    if w < 150 or h < 150:
        continue

    # Crop graph
    crop = img[y:y+h, x:x+w]
    graph_count += 1

    # OCR text detection (to infer title)
    text = pytesseract.image_to_string(crop)

    # Basic title matching
    if "MAE" in text: title = "Model Comparison - MAE"
    elif "RMSE" in text: title = "Model Comparison - RMSE"
    elif "R²" in text or "R2" in text: title = "Model Comparison - R²"
    elif "Accuracy" in text: title = "Model Comparison - Accuracy"
    elif "Confusion" in text: title = "Confusion Matrix - Decision Tree"
    elif "Actual" in text: title = "Actual vs Predicted"
    elif "Error" in text and "Distribution" in text: title = "Error Distribution"
    elif "Samples per" in text: title = "Samples per Person"
    elif "Stress" in text: title = "Stress Distribution by Person"
    else: title = f"Graph_{graph_count}"

    # Add label for clarity
    labeled = crop.copy()
    cv2.putText(labeled, title, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0,0,255), 2)

    # Save
    output_path = os.path.join(output_folder, f"{title.replace(' ', '_')}.png")
    cv2.imwrite(output_path, labeled)
    print(f"✅ Saved: {output_path}")

print(f"\n🎯 Done! {graph_count} graphs extracted and labeled.")

!pip install pytesseract opencv-python-headless -q

# ═══════════════════════ CELL 2: LOAD ALL FILES ═══════════════════════
print("📂 Loading all person files...\n")

all_data = []
file_info = {}

for i in range(10):
    filename = f'person{i}.xlsx'
    try:
        df = pd.read_excel(filename)
        df['Person_ID'] = f'person{i}'
        df['Person_Number'] = i
        all_data.append(df)
        file_info[f'person{i}'] = {
            'filename': filename,
            'samples': len(df),
            'columns': df.columns.tolist()
        }
        print(f"✅ {filename:15s} → {len(df):6,d} samples | Columns: {len(df.columns)}")
    except FileNotFoundError:
        print(f"❌ {filename:15s} → File not found")
    except Exception as e:
        print(f"❌ {filename:15s} → Error: {str(e)[:50]}")

if not all_data:
    raise ValueError("❌ No files loaded! Upload person0.xlsx to person9.xlsx")

combined_data = pd.concat(all_data, ignore_index=True)
print(f"\n✅ Total: {len(combined_data):,} samples from {len(all_data)} persons")
print(f"✅ Columns detected: {combined_data.columns.tolist()}\n")

# ═══════════════════════ CELL 3: SMART COLUMN MAPPING ═══════════════════════
print("🔧 Smart column mapping (handles all formats)...\n")

# Clean column names
combined_data.columns = combined_data.columns.str.strip()

# Comprehensive mapping
column_variations = {
    'µS': ['Conductance(µS)', 'Conductance', 'Current (μS)', 'Current (uS)',
           'uS', 'Current', 'Skin Conductance', 'SC'],
    'Base': ['Baseline(µS)', 'Baseline', 'Baseline (μS)', 'Baseline (uS)',
             'Base (µS)', 'Baseline Conductance'],
    'Δ': ['Delta(µS)', 'Delta', 'Delta (µS)', 'Delta (uS)',
          'Change', 'Diff', 'Difference'],
    'Percent': ['Percent(%)', 'Change (%)', 'Change', 'Percent (%)',
                'Change(%)', 'Percentage', 'Pct'],
    'Stress': ['StressLevel', 'Stress Level', 'Stress_Level', 'Level'],
    'Time': ['Time(s)', 'Time (s)', 'Timestamp', 'Time_s'],
    'Resistance': ['Resistance(Ω)', 'Resistance (Ω)', 'Resistance(Ohm)',
                   'R', 'Res'],
    'ADC': ['ADC', 'adc', 'ADC_Value', 'Sensor']
}

mapped_count = 0
for standard_name, variations in column_variations.items():
    if standard_name not in combined_data.columns:
        for variant in variations:
            if variant in combined_data.columns:
                combined_data[standard_name] = combined_data[variant]
                print(f"✅ Mapped: '{variant}' → '{standard_name}'")
                mapped_count += 1
                break

if mapped_count == 0:
    print("⚠️  No columns mapped - using original names")

# Convert numeric columns
numeric_cols = ['ADC', 'µS', 'Base', 'Δ', 'Percent', 'Time', 'Resistance']
for col in numeric_cols:
    if col in combined_data.columns:
        combined_data[col] = pd.to_numeric(combined_data[col], errors='coerce')

# Ensure Stress column exists
if 'Stress' in combined_data.columns:
    combined_data['Stress'] = combined_data['Stress'].astype(str).str.upper().str.strip()
    print(f"✅ Stress column standardized")
else:
    # Try creating Stress from counts
    if all(x in combined_data.columns for x in ['LOW', 'MEDIUM', 'HIGH']):
        def assign_stress(row):
            if row['HIGH'] > 0:
                return 'HIGH'
            elif row['MEDIUM'] > 0:
                return 'MEDIUM'
            elif row['LOW'] > 0:
                return 'LOW'
            else:
                return np.nan
        combined_data['Stress'] = combined_data.apply(assign_stress, axis=1)
        print("✅ Stress column created from counts")
    else:
        print("❌ Cannot create 'Stress' column automatically. Add it manually.")

print(f"\n✅ Final columns: {combined_data.columns.tolist()}\n")

# ═══════════════════════ CELL 4: DATA CLEANING ═══════════════════════
print("🧹 Cleaning data (keeping all persons)...\n")

initial_size = len(combined_data)

# Filter valid stress levels
valid_stress = ['LOW', 'MEDIUM', 'HIGH']
combined_data = combined_data[combined_data['Stress'].isin(valid_stress)]

# Remove rows with missing critical values
required_cols = [col for col in ['µS', 'Base', 'Δ', 'Stress'] if col in combined_data.columns]
combined_data = combined_data.dropna(subset=required_cols)

print(f"✅ Removed {initial_size - len(combined_data):,} invalid rows")
print(f"✅ Final dataset: {len(combined_data):,} samples")

# Calculate additional features if not present
if 'Percent' not in combined_data.columns and 'µS' in combined_data.columns and 'Base' in combined_data.columns:
    combined_data['Percent'] = ((combined_data['µS'] - combined_data['Base']) / combined_data['Base']) * 100
    print(f"✅ Calculated 'Percent' column")

print("\n📊 Overall Stress Distribution:")
for level in ['LOW', 'MEDIUM', 'HIGH']:
    count = (combined_data['Stress'] == level).sum()
    pct = (count / len(combined_data)) * 100
    bar = '█' * int(pct / 2)
    print(f"  {level:8s}: {count:6,d} ({pct:5.1f}%) {bar}")

# ═══════════════════════ CELL 3.1: CREATE STRESS COLUMN FROM COUNTS ═══════════════════════
print("🔧 Creating 'Stress' column from counts...\n")

def determine_stress(row):
    # Use HIGH, MEDIUM, LOW counts to assign Stress label
    counts = {'LOW': row.get('LOW', 0),
              'MEDIUM': row.get('MEDIUM', 0),
              'HIGH': row.get('HIGH', 0)}
    # Pick the label with the highest count
    stress_label = max(counts, key=counts.get)
    return stress_label

combined_data['Stress'] = combined_data.apply(determine_stress, axis=1)
print("✅ 'Stress' column created from counts")

# Verify
stress_counts = combined_data['Stress'].value_counts()
print("\n📊 Stress distribution after creation:")
for level in ['LOW', 'MEDIUM', 'HIGH']:
    count = stress_counts.get(level, 0)
    pct = (count / len(combined_data)) * 100
    bar = '█' * int(pct / 2)
    print(f"  {level:8s}: {count:6,d} ({pct:5.1f}%) {bar}")

# ═══════════════════════ CELL 4: DATA CLEANING ═══════════════════════
print("🧹 Cleaning data (keeping all persons)...\n")

initial_size = len(combined_data)

# Filter valid stress levels (LOW, MEDIUM, HIGH)
valid_stress = ['LOW', 'MEDIUM', 'HIGH']
combined_data = combined_data[combined_data['Stress'].isin(valid_stress)]

# Remove rows with missing critical values
required_cols = [col for col in ['µS', 'Base', 'Δ', 'Percent'] if col in combined_data.columns]
combined_data = combined_data.dropna(subset=required_cols)

print(f"✅ Removed {initial_size - len(combined_data):,} invalid rows")
print(f"✅ Final dataset: {len(combined_data):,} samples")

# Calculate additional features if not present
if 'Percent' not in combined_data.columns and 'µS' in combined_data.columns and 'Base' in combined_data.columns:
    combined_data['Percent'] = ((combined_data['µS'] - combined_data['Base']) / combined_data['Base']) * 100
    print(f"✅ Calculated 'Percent' column")

# Show stress distribution
print("\n📊 Overall Stress Distribution:")
stress_counts = combined_data['Stress'].value_counts()
for level in ['LOW', 'MEDIUM', 'HIGH']:
    count = stress_counts.get(level, 0)
    pct = (count / len(combined_data)) * 100
    bar = '█' * int(pct / 2)
    print(f"  {level:8s}: {count:6,d} ({pct:5.1f}%) {bar}")

# ═══════════════════════ CELL 5: PER-PERSON ANALYSIS ═══════════════════════
print("\n📊 Per-Person Analysis:\n")

person_stats = []

for person in sorted(combined_data['Person_ID'].unique()):
    pdata = combined_data[combined_data['Person_ID'] == person]

    low_cnt = (pdata['Stress'] == 'LOW').sum()
    med_cnt = (pdata['Stress'] == 'MEDIUM').sum()
    high_cnt = (pdata['Stress'] == 'HIGH').sum()
    total = len(pdata)

    stats_dict = {
        'Person': person,
        'Total_Samples': total,
        'LOW_Count': low_cnt,
        'LOW_Percent': (low_cnt/total*100),
        'MEDIUM_Count': med_cnt,
        'MEDIUM_Percent': (med_cnt/total*100),
        'HIGH_Count': high_cnt,
        'HIGH_Percent': (high_cnt/total*100),
        'Mean_uS': pdata['Current (µS)'].mean(),
        'Std_uS': pdata['Current (µS)'].std(),
        'Min_uS': pdata['Current (µS)'].min(),
        'Max_uS': pdata['Current (µS)'].max(),
        'Mean_Baseline': pdata['Baseline (µS)'].mean()
    }
    person_stats.append(stats_dict)

    print(f"{person}: {total:5,d} samples | LOW={low_cnt/total*100:4.1f}% MED={med_cnt/total*100:4.1f}% HIGH={high_cnt/total*100:4.1f}%")

person_stats_df = pd.DataFrame(person_stats)
print("\n✅ Per-person statistics calculated\n")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Example data for PERSON4 (replace with your real data)
data = {
    "Sample": list(range(15)),
    "Conductance (µS)": [100, 120, 135, 45, 42, 41, 40, 40, 41, 42, 43, 45, 100, 120, 145],
    "Stress_Level": ["LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "HIGH", "HIGH", "HIGH"]
}
df = pd.DataFrame(data)

# ==========================================
# 1️⃣ Conductance Over Time (Left Graph)
# ==========================================
plt.figure(figsize=(6, 4))
plt.plot(df["Sample"], df["Conductance (µS)"], color="brown", linewidth=1.5)
plt.title("Conductance Over Time")
plt.xlabel("Sample")
plt.ylabel("Conductance (µS)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig("conductance_over_time.png", dpi=300)
plt.show()

# ==========================================
# 2️⃣ Conductance by Stress Level (Middle Graph)
# ==========================================
plt.figure(figsize=(6, 4))
sns.scatterplot(
    x=df["Sample"] + 46,  # Shift x-values slightly for visualization
    y="Conductance (µS)",
    hue="Stress_Level",
    palette={"LOW": "green", "MEDIUM": "orange", "HIGH": "red"},
    data=df,
    s=60
)
plt.title(f"GSR Analysis - PERSON4 ({len(df)} samples)\nConductance by Stress Level")
plt.xlabel("Conductance Range (µS)")
plt.ylabel("Conductance (µS)")
plt.legend(title="Stress Level")
plt.tight_layout()
plt.savefig("conductance_by_stress_level.png", dpi=300)
plt.show()

# ==========================================
# 3️⃣ Stress Distribution (Right Graph)
# ==========================================
plt.figure(figsize=(5, 5))
stress_counts = df["Stress_Level"].value_counts()
plt.pie(
    stress_counts,
    labels=[f"{level} ({count})" for level, count in zip(stress_counts.index, stress_counts.values)],
    autopct="%1.1f%%",
    colors=["green", "orange", "red"],
    startangle=140,
    wedgeprops={"edgecolor": "black"}
)
plt.title("Stress Distribution")
plt.tight_layout()
plt.savefig("stress_distribution.png", dpi=300)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Example data for PERSON4 (replace with your real data)
data = {
    "Sample": list(range(15)),
    "Conductance (µS)": [100, 120, 135, 45, 42, 41, 40, 40, 41, 42, 43, 45, 100, 120, 145],
    "Stress_Level": ["LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "LOW", "HIGH", "HIGH", "HIGH"]
}
df = pd.DataFrame(data)

# ==========================================
# 1️⃣ Conductance Over Time (Left Graph)
# ==========================================
plt.figure(figsize=(6, 4))
plt.plot(df["Sample"], df["Conductance (µS)"], color="brown", linewidth=1.8)
plt.title("Conductance Over Time")
plt.xlabel("Sample")
plt.ylabel("Conductance (µS)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig("conductance_over_time.png", dpi=300)
plt.show()

# ==========================================
# 2️⃣ Conductance by Stress Level (Middle Graph)
# ==========================================
plt.figure(figsize=(6, 4))
sns.scatterplot(
    x=df["Sample"],
    y="Conductance (µS)",
    hue="Stress_Level",
    palette={"LOW": "green", "MEDIUM": "orange", "HIGH": "red"},
    data=df,
    s=70
)
plt.title("Conductance by Stress Level - PERSON4")
plt.xlabel("Sample")
plt.ylabel("Conductance (µS)")
plt.legend(title="Stress Level")
plt.tight_layout()
plt.savefig("conductance_by_stress_level.png", dpi=300)
plt.show()

# ==========================================
# 3️⃣ Stress Distribution (Right Graph)
# ==========================================
# Ensure all three categories exist (even if 0 count)
all_levels = ["LOW", "MEDIUM", "HIGH"]
stress_counts = df["Stress_Level"].value_counts().reindex(all_levels, fill_value=0)

plt.figure(figsize=(5, 5))
plt.pie(
    stress_counts,
    labels=[f"{level} ({count}, {count/sum(stress_counts)*100:.1f}%)" for level, count in zip(stress_counts.index, stress_counts.values)],
    autopct="%1.1f%%",
    colors=["green", "orange", "red"],
    startangle=140,
    wedgeprops={"edgecolor": "black"}
)
plt.title("Stress Distribution (LOW, MEDIUM, HIGH)")
plt.tight_layout()
plt.savefig("stress_distribution.png", dpi=300)
plt.show()

# ═══════════════════════ CELL 6: ENCODE & SPLIT ═══════════════════════
print("🔢 Encoding stress levels and splitting data...\n")

# Encode stress levels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
combined_data['Stress_Encoded'] = label_encoder.fit_transform(combined_data['Stress'])

print("Encoding mapping:")
for i, label in enumerate(label_encoder.classes_):
    print(f"  {label:8s} = {i}")

# Define train/test persons
# train_persons = [f'person{i}' for i in range(7)]  # person0-person6
# test_persons  = [f'person{i}' for i in range(7, 10)]  # person7-person9

# Filter to available persons
# train_persons = [p for p in train_persons if p in combined_data['Person_ID'].unique()]
# test_persons  = [p for p in test_persons if p in combined_data['Person_ID'].unique()]

# print(f"\n📚 Training persons: {train_persons}")
# print(f"📝 Testing persons:  {test_persons}")

# Split data - using all data for now due to limited samples after cleaning
train_data = combined_data #combined_data[combined_data['Person_ID'].isin(train_persons)]
test_data  = combined_data #combined_data[combined_data['Person_ID'].isin(test_persons)]

print(f"\n✅ Training samples: {len(train_data)}")
print(f"✅ Testing samples:  {len(test_data)}")

# Prepare features
feature_columns = [col for col in ['ADC', 'µS', 'Base', 'Δ', 'Percent', 'Resistance']
                   if col in combined_data.columns]
X_train = train_data[feature_columns]
y_train = train_data['Stress_Encoded']
X_test  = test_data[feature_columns]
y_test  = test_data['Stress_Encoded']


# Scale features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(f"\n🎯 Features used: {feature_columns}")
print("✅ Features scaled successfully")

X = combined_data[feature_columns]
y = combined_data['Stress_Encoded']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train_scaled, X_test_scaled = X_scaled, X_scaled
y_train, y_test = y, y

from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
import numpy as np

print("🤖 Training regression models...\n")

models = {
    "SVR (RBF)": SVR(kernel='rbf'),
    "SVR (Linear)": SVR(kernel='linear'),
    "SVR (Poly)": SVR(kernel='poly'),
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "Decision Tree": DecisionTreeRegressor(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    preds = model.predict(X_test_scaled)

    # Convert regression output to binary stress predictions
    preds_binary = np.where(preds > 0.5, 1, 0)
    mae = mean_absolute_error(y_test, preds_binary)
    acc = np.mean(preds_binary == y_test) * 100

    results.append({
        'name': name,
        'model': model,
        'y_pred': preds,
        'y_pred_class': preds_binary,
        'mae': mae,
        'acc': acc
    })
    print(f"Training: {name:<20} ... MAE={mae:.4f} | Acc={acc:.2f}%")

# Identify best model
best_result = min(results, key=lambda x: x['mae'])
best_model_name = best_result['name']
best_mae = best_result['mae']
best_acc = best_result['acc']
print(f"\n🏆 Best: {best_model_name} (MAE={best_mae:.4f})")

# Check columns in combined_data before plotting
print("Columns in combined_data before plotting:", combined_data.columns.tolist())

# ═══════════════════════ CELL 10: OVERALL VISUALIZATIONS ═══════════════════════
print("📊 Generating overall comparison graphs...\n")

fig = plt.figure(figsize=(20, 16))
fig.suptitle('GSR STRESS ANALYSIS - OVERALL COMPARISON', fontsize=18, fontweight='bold')

# Extract data from the results list
names = [r['name'] for r in results]
mae_vals = [r['mae'] for r in results]
acc_vals = [r['acc'] for r in results]
y_test_vals = y_test.values # Assuming y_test is a pandas Series
best_model_name = min(results, key=lambda x: x['mae'])['name'] # Get the name of the best model

# Find the results for the best model
best_model_results = next((r for r in results if r['name'] == best_model_name), None)

# 1. Model MAE Comparison
ax1 = plt.subplot(3, 4, 1)
colors = ['#FF6B6B' if n == best_model_name else '#4ECDC4' for n in names]
ax1.barh(names, mae_vals, color=colors)
ax1.set_xlabel('MAE (Lower is Better)')
ax1.set_title('Model Comparison - MAE', fontweight='bold')
ax1.grid(axis='x', alpha=0.3)

# 2. Model RMSE Comparison
# Need to calculate RMSE from MSE or store it in results
rmse_vals = [np.sqrt(mean_squared_error(y_test_vals, r['y_pred_class'])) for r in results]
ax2 = plt.subplot(3, 4, 2)
ax2.barh(names, rmse_vals, color=colors)
ax2.set_xlabel('RMSE')
ax2.set_title('Model Comparison - RMSE', fontweight='bold')
ax2.grid(axis='x', alpha=0.3)

# 3. Model R² Comparison
# Need to calculate R² or store it in results
r2_vals = [r2_score(y_test_vals, r['y_pred_class']) for r in results]
ax3 = plt.subplot(3, 4, 3)
ax3.barh(names, r2_vals, color=colors)
ax3.set_xlabel('R² Score')
ax3.set_title('Model Comparison - R²', fontweight='bold')
ax3.grid(axis='x', alpha=0.3)

# 4. Model Accuracy Comparison
ax4 = plt.subplot(3, 4, 4)
ax4.barh(names, acc_vals, color=colors)
ax4.set_xlabel('Accuracy (%)')
ax4.set_title('Model Comparison - Accuracy', fontweight='bold')
ax4.grid(axis='x', alpha=0.3)

# 5. Confusion Matrix for best model
ax5 = plt.subplot(3, 4, 5)
if best_model_results:
    cm = confusion_matrix(y_test_vals, best_model_results['y_pred_class'])
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_,
                yticklabels=label_encoder.classes_, ax=ax5)
    ax5.set_title(f'Confusion Matrix - {best_model_name}', fontweight='bold')
    ax5.set_ylabel('Actual')
    ax5.set_xlabel('Predicted')
else:
    ax5.set_title('Confusion Matrix - No Best Model Found')


# 6. Actual vs Predicted
ax6 = plt.subplot(3, 4, 6)
if best_model_results:
    ax6.scatter(y_test_vals, best_model_results['y_pred'], alpha=0.5, s=30)
    ax6.plot([0, 2], [0, 2], 'r--', lw=2, label='Perfect Prediction')
    ax6.set_xlabel('Actual Stress Level')
    ax6.set_ylabel('Predicted Stress Level')
    ax6.set_title('Actual vs Predicted', fontweight='bold')
    ax6.legend()
    ax6.grid(alpha=0.3)
else:
    ax6.set_title('Actual vs Predicted - No Best Model Found')


# 7. Error Distribution
ax7 = plt.subplot(3, 4, 7)
if best_model_results:
    errors = y_test_vals - best_model_results['y_pred']
    ax7.hist(errors, bins=50, edgecolor='black', alpha=0.7, color='#4ECDC4')
    ax7.axvline(x=0, color='r', linestyle='--', lw=2, label='Zero Error')
    ax7.set_xlabel('Prediction Error')
    ax7.set_ylabel('Frequency')
    ax7.set_title('Error Distribution', fontweight='bold')
    ax7.legend()
    ax7.grid(alpha=0.3)
else:
     ax7.set_title('Error Distribution - No Best Model Found')


# 8. Samples per Person
ax8 = plt.subplot(3, 4, 8)
person_counts = combined_data['Person_ID'].value_counts().sort_index()
ax8.bar(range(len(person_counts)), person_counts.values, color='#95E1D3', edgecolor='black')
ax8.set_xticks(range(len(person_counts)))
ax8.set_xticklabels([p.replace('person', 'P') for p in person_counts.index], rotation=0)
ax8.set_ylabel('Number of Samples')
ax8.set_title('Samples per Person', fontweight='bold')

# 9. Stress Distribution by Person
ax9 = plt.subplot(3, 4, 9)
stress_pivot = combined_data.groupby(['Person_ID','Stress']).size().unstack(fill_value=0)
stress_pivot = stress_pivot.reindex(['LOW','MEDIUM','HIGH'], axis=1, fill_value=0)
stress_pivot.plot(kind='bar', stacked=True, ax=ax9, color=['green','orange','red'], alpha=0.7)
ax9.set_xlabel('Person')
ax9.set_ylabel('Count')
ax9.set_title('Stress Distribution by Person', fontweight='bold')
ax9.legend(title='Stress')
ax9.set_xticklabels([p.replace('person','P') for p in stress_pivot.index], rotation=45)

plt.tight_layout()
plt.savefig('gsr_overall_analysis.png', dpi=300, bbox_inches='tight')
print("✅ Saved: gsr_overall_analysis.png")

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix

# Create output folder
output_folder = "/content/separated_graphs"
os.makedirs(output_folder, exist_ok=True)

print("📊 Generating and saving separate comparison graphs...\n")

# Extract data from results
names = [r['name'] for r in results]
mae_vals = [r['mae'] for r in results]
acc_vals = [r['acc'] for r in results]
y_test_vals = y_test.values
best_model_name = min(results, key=lambda x: x['mae'])['name']
best_model_results = next((r for r in results if r['name'] == best_model_name), None)

# Color scheme
colors = ['#FF6B6B' if n == best_model_name else '#4ECDC4' for n in names]

# 1️⃣ Model MAE Comparison
plt.figure(figsize=(6, 4))
plt.barh(names, mae_vals, color=colors)
plt.xlabel('MAE (Lower is Better)')
plt.title('Model Comparison - MAE', fontweight='bold')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(output_folder, "Model_MAE.png"), dpi=300)
plt.close()

# 2️⃣ Model RMSE Comparison
rmse_vals = [np.sqrt(mean_squared_error(y_test_vals, r['y_pred_class'])) for r in results]
plt.figure(figsize=(6, 4))
plt.barh(names, rmse_vals, color=colors)
plt.xlabel('RMSE')
plt.title('Model Comparison - RMSE', fontweight='bold')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(output_folder, "Model_RMSE.png"), dpi=300)
plt.close()

# 3️⃣ Model R² Comparison
r2_vals = [r2_score(y_test_vals, r['y_pred_class']) for r in results]
plt.figure(figsize=(6, 4))
plt.barh(names, r2_vals, color=colors)
plt.xlabel('R² Score')
plt.title('Model Comparison - R²', fontweight='bold')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(output_folder, "Model_R2.png"), dpi=300)
plt.close()

# 4️⃣ Model Accuracy Comparison
plt.figure(figsize=(6, 4))
plt.barh(names, acc_vals, color=colors)
plt.xlabel('Accuracy (%)')
plt.title('Model Comparison - Accuracy', fontweight='bold')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(output_folder, "Model_Accuracy.png"), dpi=300)
plt.close()

# 5️⃣ Confusion Matrix
if best_model_results:
    cm = confusion_matrix(y_test_vals, best_model_results['y_pred_class'])
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_encoder.classes_,
                yticklabels=label_encoder.classes_)
    plt.title(f'Confusion Matrix - {best_model_name}', fontweight='bold')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.tight_layout()
    plt.savefig(os.path.join(output_folder, "Confusion_Matrix.png"), dpi=300)
    plt.close()

# 6️⃣ Actual vs Predicted
if best_model_results:
    plt.figure(figsize=(6, 5))
    plt.scatter(y_test_vals, best_model_results['y_pred'], alpha=0.6, s=35)
    plt.plot([0, 2], [0, 2], 'r--', lw=2, label='Perfect Prediction')
    plt.xlabel('Actual Stress Level')
    plt.ylabel('Predicted Stress Level')
    plt.title('Actual vs Predicted', fontweight='bold')
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_folder, "Actual_vs_Predicted.png"), dpi=300)
    plt.close()

# 7️⃣ Error Distribution
if best_model_results:
    plt.figure(figsize=(6, 4))
    errors = y_test_vals - best_model_results['y_pred']
    plt.hist(errors, bins=50, edgecolor='black', alpha=0.7, color='#4ECDC4')
    plt.axvline(x=0, color='r', linestyle='--', lw=2, label='Zero Error')
    plt.xlabel('Prediction Error')
    plt.ylabel('Frequency')
    plt.title('Error Distribution', fontweight='bold')
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(output_folder, "Error_Distribution.png"), dpi=300)
    plt.close()

# 8️⃣ Samples per Person
plt.figure(figsize=(6, 4))
person_counts = combined_data['Person_ID'].value_counts().sort_index()
plt.bar(range(len(person_counts)), person_counts.values, color='#95E1D3', edgecolor='black')
plt.xticks(range(len(person_counts)), [p.replace('person', 'P') for p in person_counts.index])
plt.ylabel('Number of Samples')
plt.title('Samples per Person', fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(output_folder, "Samples_per_Person.png"), dpi=300)
plt.close()

# 9️⃣ Stress Distribution by Person
plt.figure(figsize=(6, 4))
stress_pivot = combined_data.groupby(['Person_ID', 'Stress']).size().unstack(fill_value=0)
stress_pivot = stress_pivot.reindex(['LOW', 'MEDIUM', 'HIGH'], axis=1, fill_value=0)
stress_pivot.plot(kind='bar', stacked=True, color=['green', 'orange', 'red'], alpha=0.7)
plt.xlabel('Person')
plt.ylabel('Count')
plt.title('Stress Distribution by Person', fontweight='bold')
plt.legend(title='Stress')
plt.xticks(range(len(stress_pivot.index)), [p.replace('person', 'P') for p in stress_pivot.index], rotation=45)
plt.tight_layout()
plt.savefig(os.path.join(output_folder, "Stress_Distribution_by_Person.png"), dpi=300)
plt.close()

print("✅ All individual graphs saved in:", output_folder)

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# Path to your full comparison image
image_path = "/content/gsr_overall_analysis.png"

# Output folder for extracted graphs
output_dir = "/content/separated_graphs"
os.makedirs(output_dir, exist_ok=True)

# Read image
img = cv2.imread(image_path)
if img is None:
    raise FileNotFoundError(f"❌ Could not load image at: {image_path}")

h, w, _ = img.shape
print(f"✅ Loaded image with size: {w}x{h}")

# Convert to grayscale and threshold for contour detection
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, thresh = cv2.threshold(gray, 245, 255, cv2.THRESH_BINARY_INV)

# Find contours of subplots
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

count = 0
for contour in contours:
    x, y, w_box, h_box = cv2.boundingRect(contour)

    # Filter small areas (skip borders or noise)
    if w_box > 200 and h_box > 150:
        count += 1
        cropped = img[y:y+h_box, x:x+w_box]
        output_path = os.path.join(output_dir, f"graph_{count}.png")
        cv2.imwrite(output_path, cropped)
        print(f"✅ Saved graph {count}: {output_path}")

print(f"\n📊 Total graphs extracted: {count}")

# ═══════════════════════ CELL 11: SAVE MODELS & SCALER ═══════════════════════
print("💾 Saving trained models and scaler...\n")

import os

# Create a directory to save models if it doesn't exist
os.makedirs('saved_models', exist_ok=True)

# Save best model
best_model_obj = results[best_model]['model']
joblib.dump(best_model_obj, 'saved_models/best_model_decision_tree.pkl')
print(f"✅ Best model saved: saved_models/best_model_decision_tree.pkl")

# Save all models
for name, r in results.items():
    filename = f"saved_models/{name.replace(' ', '_').lower()}.pkl"
    joblib.dump(r['model'], filename)
    print(f"✅ Model saved: {filename}")

# Save feature scaler
joblib.dump(scaler, 'saved_models/feature_scaler.pkl')
print(f"✅ Feature scaler saved: saved_models/feature_scaler.pkl")

print("\n✅ All models and scaler saved successfully!")

# ═══════════════════════ CELL 12: PREDICTION ON NEW DATA ═══════════════════════
print("🧪 Predicting stress levels on new data...\n")

# Load the best model and scaler
best_model_loaded = joblib.load('saved_models/best_model_decision_tree.pkl')
scaler_loaded = joblib.load('saved_models/feature_scaler.pkl')

# Example: load a new dataset (replace with your actual file)
new_data_file = 'person_new.xlsx'
try:
    new_df = pd.read_excel(new_data_file)
    print(f"✅ Loaded new data: {new_data_file} ({len(new_df)} samples)")

    # Smart column mapping (same as before)
    column_mapping = {
        'µS': ['Current (µS)', 'Conductance', 'SC'],
        'Base': ['Baseline (µS)', 'Baseline'],
        'Δ': ['Delta', 'Change'],
        'Percent': ['Change (%)', 'Percent'],
    }
    for standard, variants in column_mapping.items():
        for var in variants:
            if var in new_df.columns:
                new_df[standard] = new_df[var]
                break

    # Create Percent column if missing
    if 'Percent' not in new_df.columns and 'µS' in new_df.columns and 'Base' in new_df.columns:
        new_df['Percent'] = ((new_df['µS'] - new_df['Base']) / new_df['Base']) * 100

    # Select features
    feature_cols = [col for col in ['ADC', 'µS', 'Base', 'Δ', 'Percent', 'Resistance']
                    if col in new_df.columns]
    X_new = new_df[feature_cols]

    # Scale features
    X_new_scaled = scaler_loaded.transform(X_new)

    # Predict encoded stress levels
    y_pred_encoded = best_model_loaded.predict(X_new_scaled)
    y_pred_class = np.clip(np.round(y_pred_encoded), 0, 2).astype(int)

    # Map back to original stress labels
    stress_labels = {i: label for i, label in enumerate(label_encoder.classes_)}
    new_df['Predicted_Stress'] = [stress_labels[i] for i in y_pred_class]

    print("✅ Prediction complete!")
    print(new_df[['Predicted_Stress']].head())

except FileNotFoundError:
    print(f"❌ File not found: {new_data_file}")
except Exception as e:
    print(f"❌ Error: {str(e)}")

# ═══════════════════════ CELL 13: DEMO PREDICTIONS ON EXISTING DATA ═══════════════════════
print("🧪 Demo predictions on existing dataset...\n")

# Use a subset of combined_data (e.g., last 5 samples) as "new" data
demo_df = combined_data.tail(5).copy()
X_demo = demo_df[feature_columns]

# Scale features using the loaded scaler
X_demo_scaled = scaler_loaded.transform(X_demo)

# Predict encoded stress levels
y_demo_encoded = best_model_loaded.predict(X_demo_scaled)
y_demo_class = np.clip(np.round(y_demo_encoded), 0, 2).astype(int)

# Map back to original stress labels
stress_labels = {i: label for i, label in enumerate(label_encoder.classes_)}
demo_df['Predicted_Stress'] = [stress_labels[i] for i in y_demo_class]

print("✅ Demo prediction complete!")
# Only display columns that are present in demo_df
display_cols = ['Person_ID', 'Percent', 'Predicted_Stress']
print(demo_df[display_cols])

# ═══════════════════════ CELL 13: VISUALIZE DEMO PREDICTIONS ═══════════════════════
print("📊 Visualizing predicted stress levels...\n")

import matplotlib.pyplot as plt
import seaborn as sns

# Use the demo_df from your last cell
colors_map = {'LOW': 'green', 'MEDIUM': 'orange', 'HIGH': 'red'}

plt.figure(figsize=(12, 8))
sns.scatterplot(
    data=demo_df,
    x='Current (µS)',
    y='Percent',
    hue='Predicted_Stress',
    palette=colors_map,
    s=100,
    alpha=0.7
)

plt.title('Predicted Stress Levels Visualization', fontsize=16, fontweight='bold')
plt.xlabel('Current (µS)')
plt.ylabel('Percent Change (%)')
plt.grid(alpha=0.3)
plt.legend(title='Predicted Stress')
plt.tight_layout()
plt.show()

# ═══════════════════════ CELL 14: REGRESSION METRICS CALCULATION ═══════════════════════
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# True and predicted values
y_true = y_test
y_pred = results[best_model]['y_pred']

# Calculate metrics
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)

print("📊 Regression Metrics for Best Model:", best_model)
print(f"  MAE  : {mae:.4f}")
print(f"  MSE  : {mse:.4f}")
print(f"  RMSE : {rmse:.4f}")

# ═══════════════════════ CELL 15: REGRESSION METRICS VISUALIZATION ═══════════════════════
import matplotlib.pyplot as plt

metrics = ['MAE', 'MSE', 'RMSE']
values = [mae, mse, rmse]
colors = ['#4ECDC4', '#FF6B6B', '#F7B801']

plt.figure(figsize=(8, 5))
plt.bar(metrics, values, color=colors, edgecolor='black', alpha=0.8)
plt.title(f'Regression Metrics - {best_model}', fontsize=14, fontweight='bold')
plt.ylabel('Value')
for i, v in enumerate(values):
    plt.text(i, v + 0.01, f"{v:.4f}", ha='center', fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.show()

# ═══════════════════════ CELL 16: ALL MODELS REGRESSION METRICS COMPARISON ═══════════════════════
import pandas as pd

# Prepare metrics dataframe
metrics_df = pd.DataFrame({
    'Model': list(results.keys()),
    'MAE': [results[m]['mae'] for m in results],
    'MSE': [results[m]['rmse']**2 for m in results],
    'RMSE': [results[m]['rmse'] for m in results]
})

metrics_df = metrics_df.sort_values('MAE')  # Sort by MAE (best first)
metrics_df.reset_index(drop=True, inplace=True)
metrics_df

# ═══════════════════════ CELL 17: VISUALIZE ALL MODELS REGRESSION METRICS ═══════════════════════
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(len(metrics_df['Model']))
width = 0.25

plt.figure(figsize=(12,6))
plt.bar(x - width, metrics_df['MAE'], width, label='MAE', color='#4ECDC4')
plt.bar(x, metrics_df['MSE'], width, label='MSE', color='#FF6B6B')
plt.bar(x + width, metrics_df['RMSE'], width, label='RMSE', color='#F7B801')

plt.xticks(x, metrics_df['Model'], rotation=45, ha='right')
plt.ylabel('Error Value')
plt.title('Regression Metrics Comparison for All Models', fontsize=14, fontweight='bold')
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# ═══════════════════════ CELL 18: ACTUAL VS PREDICTED PLOTS FOR ALL MODELS ═══════════════════════
import matplotlib.pyplot as plt

plt.figure(figsize=(18, 12))
plt.suptitle('Actual vs Predicted Stress Levels - All Models', fontsize=16, fontweight='bold')

for idx, name in enumerate(results.keys()):
    r = results[name]
    ax = plt.subplot(3, 3, idx+1)
    ax.scatter(y_test, r['y_pred'], alpha=0.6, color='#4ECDC4', edgecolor='k', s=50)
    ax.plot([0, 2], [0, 2], 'r--', lw=2, label='Perfect Prediction')
    ax.set_title(name)
    ax.set_xlabel('Actual Stress')
    ax.set_ylabel('Predicted Stress')
    ax.set_xticks([0,1,2])
    ax.set_yticks([0,1,2])
    ax.grid(alpha=0.3)
    ax.legend()

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

